---
title: "Stat 472 Calc Project"
author: "Emma, Jackson, Amanda, Megan"
date: "3/3/2020"
output: pdf_document
---

```{r echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, fig.width = 4, fig.height = 4, tidy = TRUE)
#install.packages("dplyr")
#install.packages("tidyr")
#install.packages("knitr")
#install.packages("kableExtra")
#install.packages("forcats")

library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)
library(forcats)
```



```{r}
data <- read.csv("CSPCC_Switcher_Data.csv")
data$Q3FUS=paste(data$Q3FUS_No, data$Q3FUS_Yes)

```



```{r}
s1 <- data %>% filter(Q26 == 1, Q3FUS_No == "No") %>% mutate(Switch = 1)

s2 <- data %>% filter(Q26 == 3, Q3FUS_No == "No") %>% mutate(Switch = 1)

s3 <- data %>% filter(is.na(Q26),Q5Post == 1, Q3FUS_No == "No") %>% mutate(Switch = 1)

s4 <- data %>% filter(is.na(Q26),Q5Post == 3, Q3FUS_No == "No") %>% mutate(Switch = 1)

s5 <- data %>% filter(Q26 == 1, Q3Post == 3, Q5Post == 1, Q3FUS_No != "No", 
                      Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

s6 <- data %>% filter(Q26 ==1, Q3Post == 2, Q3FUS_No != "No", 
                      Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

s7 <- data %>% filter(Q26 == 3, Q5Post == 1, Q3Post == 3, Q3FUS_No != "No", 
                      Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

s8 <- data %>% filter(Q26 == 3, Q3Post == 2, Q3FUS_No != "No", 
                      Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

s9 <- data %>% filter(is.na(Q26), Q5Post == 1, Q3Post ==3, Q3FUS_No != "No", 
                      Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

s10 <- data %>% filter(is.na(Q26), Q5Post ==1, Q3Post ==2, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

s11 <- data %>% filter(is.na(Q26), Q5Post == 3, Q3Post ==2, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

```




```{r}
p12 <- data %>% filter(Q26 == 1, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)

p13 <- data %>% filter(Q26 == 3, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)

p14 <- data %>% filter(is.na(Q26), Q5Post == 1, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)

p15 <- data %>% filter(is.na(Q26), Q5Post == 3, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)

p16 <- data %>% filter(Q26 == 1, Q3Post == 1, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

p17 <- data %>% filter(Q26 == 1, Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

p18 <- data %>% filter(Q26 == 1, Q5Post == 2, Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes" ) %>% mutate(Switch = 0)

p19 <- data %>% filter(Q26 == 1, is.na(Q5Post), Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

p20 <- data %>% filter(Q26 == 3, Q3Post == 1, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

p21 <- data %>% filter(Q26 == 3, Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)


p22 <- data %>% filter(Q26 == 3, Q5Post == 2, Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes")  %>% mutate(Switch = 0)

p23 <- data %>% filter(Q26 == 3, is.na(Q5Post), Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes" )  %>% mutate(Switch = 0)

p24 <- data %>% filter(is.na(Q26), Q5Post == 1, Q3Post == 1, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

p25 <- data %>% filter(is.na(Q26), Q5Post == 3, Q3Post == 1, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

p26 <- data %>% filter(is.na(Q26), Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", 
                       Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)


```

```{r}

switchdata <- rbind(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,
                    s11,p12,p13,p14,p15,p16,p17,p18,
                    p19,p20,p21,p22,p23,p24,p25,p26)

```


```{r}
careerdata <- switchdata %>% 
  mutate(major = fct_collapse(factor(switchdata$Q60, levels=1:16), 
                              `1` = c("3","4","5","7","8","9"), 
                              `2` = "6", 
                              `3` = c("1","2"),
                              `4` = c("10","11","12","13","14","15"),
                              `5` = "16")) %>%
  
 filter(!(is.na(Q15_CalculusNonAPFinalGrade) & is.na(Q17_CalculusABFinalGrade) 
          & is.na(Q17_CalculusBCFinalGrade) & is.na(Q18))) %>% #filter cal exp
  
  filter(! is.na(major)) %>% #filter major
  
  filter(! (is.na(Q3_SATMath) & is.na(Q7_ACTMath))) %>% #filter no stnd test
  
  
  filter(Q3_SATMath %in% seq(200,800,10) | Q7_ACTMath %in% seq(1,36,1)) %>%
  
  filter(! is.na(Q48)) %>%#filter gender
  
  filter(! (is.na(Q18Post_Applications) & is.na(Q18Post_Appointments) 
            & is.na(Q18Post_AskedQs)
            & is.na(Q18Post_Discouraged) & is.na(Q18Post_Explanations) 
            & is.na(Q18Post_Listened) & is.na(Q18Post_ProblemSolver) 
            & is.na(Q18Post_Time))) %>% #filer instruc qual
  
filter(! (is.na(Q19Post_SpecificProblems) & is.na(Q19Post_WorkTogether) 
          & is.na(Q19Post_Discussion) & is.na(Q19Post_Presentations) 
          & is.na(Q19Post_Individually) & is.na(Q19Post_Lecture) 
          & is.na(Q19Post_AskQuestions)
          & is.na(Q19Post_ExplainThinking))) #filter student prep
  

#unique(careerdata$Q3_SATMath)

```


```{r}
## Instructor Quality 
IQ <- select(data, Q18Post_Applications, Q18Post_Appointments, Q18Post_AskedQs, 
             Q18Post_Discouraged, Q18Post_Explanations, Q18Post_Listened, 
             Q18Post_ProblemSolver, Q18Post_Time)

IQ$Q18Post_Discouraged <- 7-IQ$Q18Post_Discouraged

IQ <- na.omit(IQ)

pr_IQ <- princomp(IQ)

rescale_load_iq <- pr_IQ$loadings/sum(pr_IQ$loadings[,1])

#round(rescale_load_iq[,1],3)

```

```{r}
## Student centered
SC <- select(data, Q19Post_AskQuestions, Q19Post_Discussion, Q19Post_ExplainThinking, 
             Q19Post_Individually, Q19Post_Lecture,Q19Post_Presentations,
             Q19Post_SpecificProblems, Q19Post_WorkTogether)

SC$Q19Post_Lecture <- 7 - SC$Q19Post_Lecture

SC <- na.omit(SC)

pr_SC <- princomp(SC)

#round(pr_SC$loadings[,1],3)

rescale_load_sc <- pr_SC$loadings/sum(pr_SC$loadings[,1])

#round(rescale_load_sc[,1],3)

```

```{r}
#Make variables for Instructor quality and student centered practices
IQcareer <- select(careerdata, Q18Post_Applications, Q18Post_Appointments, 
                   Q18Post_AskedQs, Q18Post_Discouraged, Q18Post_Explanations, 
                   Q18Post_Listened, Q18Post_ProblemSolver, Q18Post_Time)

IQcareer$Q18Post_Discouraged <- 7-IQcareer$Q18Post_Discouraged

SCcareer <- select(careerdata, Q19Post_AskQuestions, Q19Post_Discussion, 
                   Q19Post_ExplainThinking,Q19Post_Individually,Q19Post_Lecture,
                   Q19Post_Presentations,Q19Post_SpecificProblems, 
                   Q19Post_WorkTogether)

SCcareer$Q19Post_Lecture <- 7 - SCcareer$Q19Post_Lecture

careerdata <- careerdata %>% 
  mutate(Inst.Qual = apply(IQcareer,1,weighted.mean,rescale_load_iq[,1],na.rm = TRUE))

careerdata <- careerdata %>% 
  mutate(Student.Cent = apply(SCcareer,1,weighted.mean,rescale_load_sc[,1],na.rm = TRUE))

##Make vairables for High school, college, and no experience
###CURRENTLY NOT CORRECT 
try <- careerdata %>% 
  mutate(HighSchoolExp = as.numeric(I(Q15_CalculusNonAPFinalGrade %in% seq(1,12,1) 
                                        | Q17_CalculusABFinalGrade %in% seq(1,12,1) 
                                        | Q17_CalculusBCFinalGrade %in% seq(1,12,1)))) %>% 
  mutate(CollegeExp = I(Q18 == 1)) %>% 
  mutate(NoExp = I(is.na(Q15_CalculusNonAPFinalGrade) & 
                     is.na(Q17_CalculusABFinalGrade) & 
                     is.na(Q17_CalculusBCFinalGrade) & 
                     is.na(Q18)))

```

# S1

```{r}
x1=c("1", "2", "3", "4", "5", "6","7", "8", "9", "10", "11")

x2=c(count(s1), count(s2), count(s3), count(s4), count(s5), 
     count(s6), count(s7), count(s8), count(s9), count(s10), count(s11))

x3 <- c("Y","M","NA","NA","Y","Y","M","M","NA","NA","NA")

x4 <- c("","","Y","M","Y","","Y","","Y","Y","M")

x5 <- c("","","","","M","N","M","N","M","N","N")

x6 <- c("N","N","N","N","NA","NA","NA","NA","NA","NA","NA")



tabS1 <- cbind(x1,x2,x3,x4,x5,x6)

colnames(tabS1) <- c("Switcher Group", "Number of Students",
                     "Beginning of term","End of term; reflect", 
                     "End of term", "Follow Up")

rownames(tabS1) <- NULL

kable(tabS1) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```


```{r}
y1=c("12", "13", "14", "15", "16", "17", "18", 
     "19", "20", "21", "22", "23", "24", "25", "26")
y2=c(count(p12), count(p13), count(p14), count(p15), count(p16), 
     count(p17), count(p18), count(p19), count(p20), count(p21), 
     count(p22), count(p23), count(p24), count(p25), count(p26))
y3=c("Y", "M", "NA", "NA", "Y", "Y", "Y", "Y", "M", "M", "M", "M", "NA", "NA", "NA")
y4=c("", "", "Y", "M", "", "M", "N", "NA", "", "M", "N", "NA", "Y", "M", "M")
y5=c("", "", "", "", "Y", "M", "M", "M", "Y", "M", "M", "M", "Y", "Y", "M")
y6=c("Y", "Y", "Y", "Y", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA")

s1_p=cbind(y1, y2, y3, y4, y5, y6)

colnames(s1_p) <- c("Persister Group", "Number of Students",
                    "Beginning of term","End of term; reflect", 
                    "End of term", "Follow Up")

rownames(s1_p) <- NULL

kable(s1_p)%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

# S5

```{r}
##S5
s5 <- careerdata %>% group_by(major, Q48) %>% 
  summarise(N = length(Q18), Switcher = 
              round((length(which(Switch == '1'))/length(Q18))*100,1))


colnames(s5) <- c('Major', 'Gender', 'N', 'Switcher %')

s5$Major <- c("Pre-Med", "", "STEM", "", "Engineering", 
              "", "Non-STEM", "", "Undecided", "")

s5$Gender <- rep(c("Male", "Female"), 5)

kable(s5) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```

# S6

```{r}
#S6

s6 <- careerdata %>% mutate(Prev_Calc = I((!(is.na(careerdata$Q15_CalculusNonAPFinalGrade)) 
                                           | !(is.na(careerdata$Q17_CalculusABFinalGrade)) 
                                           |  !(is.na(careerdata$Q17_CalculusBCFinalGrade))) 
                                          & (careerdata$Q18 == 2 | is.na(careerdata$Q18) ))*1 
                            
                            + I(careerdata$Q18 == 1 & !is.na(careerdata$Q18))*2 
                            
                            + I((is.na(careerdata$Q15_CalculusNonAPFinalGrade)) 
                                & (is.na(careerdata$Q17_CalculusABFinalGrade)) 
                                &  (is.na(careerdata$Q17_CalculusBCFinalGrade)) 
                                & (careerdata$Q18 == 2 | is.na(careerdata$Q18)) )*3) %>%
  
  group_by(Prev_Calc,Q48) %>%
  summarise(N = length(Prev_Calc), Switcher = 
              round((length(which(Switch == '1'))/length(Prev_Calc))*100,1))


colnames(s6) <- c('Previous Calculus', 'Gender', 'N', 'Switcher %')

s6$`Previous Calculus` <- c("High School", "", "College", "", "None", "")

s6$Gender <- rep(c("Male", "Female"), 3)

kable(s6) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```


# S7

```{r}
X_SAT=careerdata$Q3_SATMath

SAT=rev(seq(200,800,by=10))

SAT_per=c(99,99, 99, 98, 97,97,96,95,95,94,93,91,90,88,87,85,83,82,79,77,75,73,70,
          67,64,62,59,55,52, 49,45,42,40,36,33,30,27,24,21,19,16,14,12,10,9, 7,6,
          5,4,3,3,2,2,1,1,1,1,1,0,0,0)

X_ACT=careerdata$Q7_ACTMath

ACT=36:1

ACT_per=c(99,99,99,98,97,96,95,93,91,88,84,79,73,67,61,56,52,47,42,36,27,15,6,2)

ACT_per=c(ACT_per, rep(1,length(ACT)-length(ACT_per)))

X_SAT=SAT_per[match(X_SAT, SAT)]

X_ACT= ACT_per[match(X_ACT, ACT)]


#head(careerdata)

careerdata$x_per=rowMeans(cbind(X_SAT, X_ACT), na.rm=TRUE)

S7 <- careerdata %>% mutate(Test_Per = I(x_per >= 90)*1 + I(x_per >= 80 & x_per < 90)*2
                            + I(x_per >= 70 & x_per < 80)*3 + I(x_per >= 60 & x_per < 70)*4
                            + I(x_per >= 50 & x_per < 60)*5 + I(x_per >= 40 & x_per < 50)*6
                            + I(x_per >= 30 & x_per < 40)*7 + I(x_per >= 20 & x_per < 30)*8
                            + I(x_per >= 10 & x_per < 20)*9+ I(x_per >= 0 & x_per < 10)*10) %>%

group_by(Test_Per, Q48) %>%
  summarise(N = length(x_per), Switcher = 
              round((length(which(Switch == '1'))/length(x_per))*100,1)) 

colnames(S7) <- c('Test_Percentile', 'Gender', 'N', 'Switcher %')

S7$Test_Percentile <- c("90-100", "", "80-89","", "70-79","", "60-69", 
                        "","50-59","", "40-49","", "30-39","", "20-29","",
                        "10-19","", "0-9","")

S7$Gender <- rep(c("Male", "Female"), 10)

kable(S7) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


```


# S8

```{r}

S8 <- careerdata %>% mutate(Instqual = I(Inst.Qual >= 5.5)*1 
                            + I(Inst.Qual < 5.5 & Inst.Qual >= 4.5)*2 
                            + I(Inst.Qual < 4.5 & Inst.Qual >= 3.5)*3 
                            + I(Inst.Qual < 3.5 & Inst.Qual >= 2.5)*4 
                            + I(Inst.Qual < 2.5 & Inst.Qual >= 1.5)*5 
                            + I(Inst.Qual < 1.5 & Inst.Qual >= 1.0)*6 ) 

S8 <- S8 %>% group_by(Instqual,Q48) %>%
  summarise(N = length(Q48) , Switcher = round((length(which(Switch == '1'))/length(Q48))*100,1) )

colnames(S8) <- c('IQR', 'Gender', 'N', 'Switcher %')

S8$`IQR` <- c("[5.5, 6]", "", "[4.5, 5.5)", "", "[3.5, 4.5)",
              "", "[2.5, 3.5)", "", "[1.5, 2.5)", "" , "[1, 1.5)", "")

S8$Gender <- rep(c("Male", "Female"), 6) 

S8s <- careerdata %>% mutate(StudCent = I(Student.Cent >= 5.5)*1 
                             + I(Student.Cent < 5.5 & Student.Cent >= 4.5)*2 
                             + I(Student.Cent < 4.5 & Student.Cent >= 3.5)*3 
                             + I(Student.Cent < 3.5 & Student.Cent >= 2.5)*4 
                             + I(Student.Cent < 2.5 & Student.Cent >= 1.5)*5 
                             + I(Student.Cent < 1.5 & Student.Cent >= 1.0)*6 ) 

S8s <- S8s %>% group_by(StudCent,Q48) %>% 
  summarise(N = length(Q48) , Switcher = round((length(which(Switch == '1'))/length(Q48))*100,1) )



colnames(S8s) <- c('SCIR', 'Gender ', 'N ', 'Switcher % ')

S8s$`SCIR` <- c("[5.5, 6]", "", "[4.5, 5.5)", "", "[3.5, 4.5)",
                "", "[2.5, 3.5)", "", "[1.5, 2.5)", "" , "[1, 1.5)", "")

S8s$`Gender ` <- rep(c("Male", "Female"), 6) 


S8 <- cbind(S8, S8s)



kable(S8)  %>% 
  kable_styling(bootstrap_options = c("striped", "hover",
                                      "condensed", "responsive"),full_width = T) %>%
  
  footnote(general = c("IQR = Instructor Quality Response",
                       "SCIR = Student-Centered Instruction Response"))



```


# Appendix

```{r show-code, ref.label = all_labels(),  echo = TRUE, eval = FALSE}

```

