---
title: "Final Project"
author: "Tigers"
date: "4/17/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(mlmRev)
library(lme4)
library(broom)
library(ggplot2)
library(kableExtra)
library(bayesplot)
library(rstanarm)
```

```{r}

###Read Files In#####
FullData <- read.csv("maalongdatafile_ANON.csv")  

smallData2 <- FullData %>% select(spr26calc2,sq5initialc2,studid, sqr26calc2, sp48gender, ip27gender, State, sq48gradel, ip28age,sq42preparecalcl, sq39jobl, sq40extral, ip14wd, ip14df, ip14c, sq18ask, sq18listen, sq18discuss, sq18time, sq18solve, sq18explain, sq18avail,sq18discourage)


postData <- read.csv("CSPCC_Data_FUSonly.csv")

####Label Student ID the same in both#####
colnames(smallData2) <- c("Q26", "Q5Post", "StudentID", "Q3Post", "Q48", "Instr_Gender", "Institution_ID", "Calc_Grade", "Instr_Age", "Instr_Prep_Calc", "Stud_Work", "Stud_Extra", "Instr_Withdraw", "Instr_Fail", "Instr_Pass", "Q18Post_AskedQs", "Q18Post_Listened", "Q18Post_Applications", "Q18Post_Time", "Q18Post_ProblemSolver", "Q18Post_Explanations", "Q18Post_Appointments", "Q18Post_Discouraged")

###Merge The Two DFs########
dat <- merge(smallData2, postData, by = 'StudentID')

```


```{r}

dat$Q18Post_Applications <- revalue(dat$Q18Post_Applications, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_Applications[dat$Q18Post_Applications==""]  <- NA
dat$Q18Post_Applications <- factor(dat$Q18Post_Applications, levels(dat$Q18Post_Applications)[c(7,3,5,4,2,6,1)])


dat$Q18Post_AskedQs <- revalue(dat$Q18Post_AskedQs, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_AskedQs[dat$Q18Post_AskedQs==""]  <- NA
dat$Q18Post_AskedQs <- factor(dat$Q18Post_AskedQs, levels(dat$Q18Post_AskedQs)[c(7,3,5,4,2,6,1)])

dat$Q18Post_Listened <- revalue(dat$Q18Post_Listened, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_Listened[dat$Q18Post_Listened==""]  <- NA
dat$Q18Post_Listened <- factor(dat$Q18Post_Listened, levels(dat$Q18Post_Listened)[c(7,3,5,4,2,6,1)])

dat$Q18Post_Time <- revalue(dat$Q18Post_Time, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_Time[dat$Q18Post_Time==""]  <- NA
dat$Q18Post_Time <- factor(dat$Q18Post_Time, levels(dat$Q18Post_Time)[c(7,3,5,4,2,6,1)])

dat$Q18Post_ProblemSolver <- revalue(dat$Q18Post_ProblemSolver, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_ProblemSolver[dat$Q18Post_ProblemSolver==""]  <- NA
dat$Q18Post_ProblemSolver <- factor(dat$Q18Post_ProblemSolver, levels(dat$Q18Post_ProblemSolver)[c(7,3,5,4,2,6,1)])

dat$Q18Post_Explanations <- revalue(dat$Q18Post_Explanations, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_Explanations[dat$Q18Post_Explanations==""]  <- NA
dat$Q18Post_Explanations <- factor(dat$Q18Post_Explanations, levels(dat$Q18Post_Explanations)[c(7,3,5,4,2,6,1)])

dat$Q18Post_Appointments <- revalue(dat$Q18Post_Appointments, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_Appointments[dat$Q18Post_Appointments==""]  <- NA
dat$Q18Post_Appointments <- factor(dat$Q18Post_Appointments, levels(dat$Q18Post_Appointments)[c(7,3,5,4,2,6,1)])

dat$Q18Post_Discouraged <- revalue(dat$Q18Post_Discouraged, c("Strongly disagree" = 1, "Slightly disagree" = 3, "Disagree" = 2, "Slightly agree" = 4, "Agree" = 5, "Strongly agree" = 6))
dat$Q18Post_Discouraged[dat$Q18Post_Discouraged==""]  <- NA
dat$Q18Post_Discouraged <- factor(dat$Q18Post_Discouraged, levels(dat$Q18Post_Discouraged)[c(7,3,5,4,2,6,1)])

dat$Q18Post_Discouraged <- as.numeric(dat$Q18Post_Discouraged)
dat$Q18Post_AskedQs <- as.numeric(dat$Q18Post_AskedQs)
dat$Q18Post_Listened <- as.numeric(dat$Q18Post_Listened)
dat$Q18Post_Applications <- as.numeric(dat$Q18Post_Applications)
dat$Q18Post_Time <- as.numeric(dat$Q18Post_Time)
dat$Q18Post_ProblemSolver <- as.numeric(dat$Q18Post_ProblemSolver)
dat$Q18Post_Explanations <- as.numeric(dat$Q18Post_Explanations)
dat$Q18Post_Appointments <- as.numeric(dat$Q18Post_Appointments)



dat$Q18Post_Discouraged <- 7 -dat$Q18Post_Discouraged



```

```{r}
dat$Q26 <- revalue(dat$Q26, c("Yes" = 1, "No" = 2, "Dont know/ Not sure/ N/A" = 3))

dat$Q3Post <- revalue(dat$Q3Post, c("Yes" = 1, "No" = 2, "Dont know/ Not sure/ N/A" = 3))

dat$Q5Post <- revalue(dat$Q5Post, c("Yes" = 1, "No" = 2, "Dont know/ Not sure/ N/A" = 3))

#dat$Q48 <- revalue(dat$Q48, c("Female" = 0, "Male" = 1))

dat$Q48 <- factor(dat$Q48, levels(dat$Q48[c(3,2,1)]))

dat$Q26[dat$Q26==""]  <- NA
dat$Q3Post[dat$Q3Post==""]  <- NA
dat$Q5Post[dat$Q5Post==""]  <- NA
dat$Q48[dat$Q48==""]  <- NA



```



```{r}

######Switcher Info#######

s1 <- dat %>% filter(Q26 == 1, Q3FUS_No == "No") %>% mutate(Switch = 1)
s2 <- dat %>% filter(Q26 == 3, Q3FUS_No == "No") %>% mutate(Switch = 1)
s3 <- dat %>% filter(is.na(Q26),Q5Post == 1, Q3FUS_No == "No") %>% mutate(Switch = 1)
s4 <- dat %>% filter(is.na(Q26),Q5Post == 3, Q3FUS_No == "No") %>% mutate(Switch = 1)
s5 <- dat %>% filter(Q26 == 1, Q3Post == 3, Q5Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)
s6 <- dat %>% filter(Q26 ==1, Q3Post == 2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)
s7 <- dat %>% filter(Q26 == 3, Q5Post == 1, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)
s8 <- dat %>% filter(Q26 == 3, Q3Post == 2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)
s9 <- dat %>% filter(is.na(Q26), Q5Post == 1, Q3Post ==3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)
s10 <- dat %>% filter(is.na(Q26), Q5Post ==1, Q3Post ==2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)
s11 <- dat %>% filter(is.na(Q26), Q5Post == 3, Q3Post ==2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 1)

```

```{r}

#########Persistor Info###########

p12 <- dat %>% filter(Q26 == 1, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)
p13 <- dat %>% filter(Q26 == 3, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)
p14 <- dat %>% filter(is.na(Q26), Q5Post == 1, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)
p15 <- dat %>% filter(is.na(Q26), Q5Post == 3, Q3FUS_Yes == "Yes") %>% mutate(Switch = 0)
p16 <- dat %>% filter(Q26 == 1, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p17 <- dat %>% filter(Q26 == 1, Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p18 <- dat %>% filter(Q26 == 1, Q5Post == 2, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes" ) %>% mutate(Switch = 0)
p19 <- dat %>% filter(Q26 == 1, is.na(Q5Post), Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p20 <- dat %>% filter(Q26 == 3, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p21 <- dat %>% filter(Q26 == 3, Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p22 <- dat %>% filter(Q26 == 3, Q5Post == 2, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes")  %>% mutate(Switch = 0)
p23 <- dat %>% filter(Q26 == 3, is.na(Q5Post), Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes" )  %>% mutate(Switch = 0)
p24 <- dat %>% filter(is.na(Q26), Q5Post == 1, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p25 <- dat %>% filter(is.na(Q26), Q5Post == 3, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)
p26 <- dat %>% filter(is.na(Q26), Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% mutate(Switch = 0)

```


```{r}

##### Combine Switch and Persist Data #######

swDat <- rbind(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,
                    s11,p12,p13,p14,p15,p16,p17,p18,
                    p19,p20,p21,p22,p23,p24,p25,p26)
```


```{r}
######FILTER#######

datF <- swDat %>%  
  
   filter( !is.na(Q48)) %>%
  
   filter(! (is.na(Q18Post_Applications) & is.na(Q18Post_Appointments) & is.na(Q18Post_AskedQs)
            & is.na(Q18Post_Discouraged) & is.na(Q18Post_Explanations) &
              is.na(Q18Post_Listened) & is.na(Q18Post_ProblemSolver) &
              is.na(Q18Post_Time))) %>% #filer instruc qual
   filter(! is.na(Instr_Age)) %>% #filter instructor age
   filter(! is.na(Instr_Gender)) %>% # filter instructor gender
   filter(! is.na(Calc_Grade)) %>% #filter students grade
   filter(! (is.na(Stud_Work) | is.na(Stud_Extra))) #%>% #filter if no work or extra listed
```

```{r}
IQ <- select(dat, Q18Post_Applications, Q18Post_Appointments, Q18Post_AskedQs, Q18Post_Discouraged, Q18Post_Explanations, Q18Post_Listened, Q18Post_ProblemSolver, Q18Post_Time)

IQ <- na.omit(IQ)

pr_IQ <- princomp(IQ)

rescale_load_iq <- pr_IQ$loadings/sum(pr_IQ$loadings[,1])

IQdatF <- select(datF, Q18Post_Applications, Q18Post_Appointments, 
                   Q18Post_AskedQs, Q18Post_Discouraged, Q18Post_Explanations,
                   Q18Post_Listened, Q18Post_ProblemSolver, Q18Post_Time)

datF <- datF %>% mutate(Inst.Qual = apply(IQdatF,1,weighted.mean,rescale_load_iq[,1],na.rm = TRUE))


```


# Mixed Model

\begin{eqnarray}
\text{log} (\frac{p_i}{1-p_i}) &=& \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \beta_3 X_{i3}  + \alpha_{\text{institution}} \\
p_i &=& \text{Probability of a student switching} \\
X_1 &=& \text{Gender of Professor} \\
X_2 &=& \text{Age of Professor} \\
X_3 &=& \text{Instrcutor Quality} \\
\alpha_{\text{institution}} &\sim& N (0, \tau^2)
\end{eqnarray}





```{r}
# ### Fit the model that we will be estimating
# model <- glmer(Switch ~  Instr_Gender + Instr_Age + Inst.Qual + Calc_Grade + (1|Institution_ID), data = datF, family = "binomial")
# 
# model
# 
# summary(model)
```


```{r}

datF <- datF %>% mutate(ExtraTime = datF$Stud_Work + datF$Stud_Extra)


```

```{r}
#Graphs

ggplot(aes(x = Instr_Gender, y = Switch), data = datF) + geom_point() + xlab("Instructor Quality") + ylab("Switcher")

ggplot(aes(x = Instr_Age, y = Switch), data = datF) + geom_point() + xlab("Instructor Age") + ylab("Switcher") + geom_smooth(method = "glm", se = FALSE, method.args = list(family = binomial))

ggplot(aes(x = Inst.Qual, fill = Switch), data = datF) + geom_histogram()

t1 <- data.frame("." = c("Female Prof", "Male Prof"), "Switcher" = c(sum(datF$Instr_Gender == 0 & datF$Switch == 1),sum(datF$Instr_Gender == 1 & datF$Switch == 1)
), "Persister" = c(sum(datF$Instr_Gender == 0 & datF$Switch == 0) ,sum(datF$Instr_Gender == 1 & datF$Switch == 0)
))


knitr::kable(t1) %>%
  kable_styling("striped", full_width = F) 

datF$Switch <- as.factor(datF$Switch)

ggplot(aes(x = Inst.Qual, color = Switch), data = datF) +
  geom_histogram(fill = "light blue",  alpha = 0.5, aes(color = as.factor(Switch))) + xlab("Instructor Quality") 
```



```{r}

datF$Instr_Gender <- as.factor(datF$Instr_Gender)
datF$Instr_Gender <- revalue(datF$Instr_Gender, c("0" = "Female", "1" = "Male"))
datF$Instr_Gender <- relevel(datF$Instr_Gender, "Male")

datF$Q48 <- factor(datF$Q48, levels(datF$Q48[c("Male","Female")]))
datF$Q48 <- relevel(datF$Q48, "Male")


fit_pool <- stan_glmer(Switch ~  Q48*Instr_Gender + Inst.Qual + Instr_Age  + Calc_Grade + ExtraTime + (1|Institution_ID), data = datF, family = binomial("logit"))

 invlogit <- plogis  # function(x) 1/(1 + exp(-x))
summary_stats <- function(posterior) {
  x <- invlogit(posterior)  # log-odds -> probabilities
  t(apply(x, 2, quantile, probs = c(0.1, 0.5, 0.9))) 
}

betas <- t(apply(as.matrix(fit_pool), 2, quantile, probs = c(0.1, 0.5, 0.9)))
pool <- summary_stats(as.matrix(fit_pool))
## launch_shinystan(fit_pool, ppd = FALSE) Website Link

lower <- exp(betas[2:8,1])
mean <- exp(betas[2:8,2])
upper <- exp(betas[2:8,3])
label <- c("Female Student","Female Instructor", "Instructor Quality", "Instructor Age", "Student's Calc 1 Grade", "Required Time for Nonschool", "Female Student*Female Instructor")
df <- data.frame(label, mean, lower, upper)
df$label <- factor(df$label, levels=rev(df$label))

fp <- ggplot(data=df, aes(x=label, y=mean, ymin=lower, ymax=upper)) +
        geom_pointrange() + 
        geom_hline(yintercept=1, lty=2) +  # add a dotted line at x=1 after flip
        coord_flip() +  # flip coordinates (puts labels on y axis)
        xlab("Label") + ylab("Odds Ratio") +
        theme_bw() +  # use a white background
        scale_y_continuous(limits=c(0,7)) + theme(legend.position = "None")
print(fp)

```


```{r}
#Table of betas with 
betas_table <- as.data.frame(pool[1:8,])

knitr::kable(betas_table) %>%
  kable_styling("striped", full_width = F)

##Histogram  of int.qual with color for switch for both males and females
hist.dat.female <- datF %>% filter(Q48 == "Female")
ggplot(aes(x = Inst.Qual, color = Switch), data = datF) +
  geom_histogram(alpha = 0.5, aes(fill = Switch)) +
  xlab("Instructor Quality") +
  facet_grid(vars(Q48))


```

