---
title: "Stat 472 Homework 4"
author: "Emma, Jackson, Amamda, Megan"
date: "4/7/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE,
                      warning = FALSE, fig.width = 4,
                      fig.height = 4, tidy = TRUE)

library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)
library(forcats)
library(ggplot2)
library(mlmRev)
library(lme4)

```


```{r readdata}
data <- read.csv("CSPCC_Switcher_Data.csv")
data$Q3FUS=paste(data$Q3FUS_No, data$Q3FUS_Yes)
```

```{r switcher}
s1 <- data %>% 
  filter(Q26 == 1, Q3FUS_No == "No") %>% 
  mutate(Switch = 1)
s2 <- data %>% 
  filter(Q26 == 3, Q3FUS_No == "No") %>% 
  mutate(Switch = 1)
s3 <- data %>% 
  filter(is.na(Q26),Q5Post == 1, Q3FUS_No == "No") %>%
  mutate(Switch = 1)
s4 <- data %>% 
  filter(is.na(Q26),Q5Post == 3, Q3FUS_No == "No") %>%
  mutate(Switch = 1)
s5 <- data %>% 
  filter(Q26 == 1, Q3Post == 3, Q5Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% 
  mutate(Switch = 1)
s6 <- data %>% 
  filter(Q26 ==1, Q3Post == 2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 1)
s7 <- data %>% 
  filter(Q26 == 3, Q5Post == 1, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% 
  mutate(Switch = 1)
s8 <- data %>% 
  filter(Q26 == 3, Q3Post == 2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% 
  mutate(Switch = 1)
s9 <- data %>%
  filter(is.na(Q26), Q5Post == 1, Q3Post ==3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 1)
s10 <- data %>% 
  filter(is.na(Q26), Q5Post ==1, Q3Post ==2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>% 
  mutate(Switch = 1)
s11 <- data %>%
  filter(is.na(Q26), Q5Post == 3, Q3Post ==2, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 1)
```

```{r persister}
p12 <- data %>%
  filter(Q26 == 1, Q3FUS_Yes == "Yes") %>% 
  mutate(Switch = 0)

p13 <- data %>% 
  filter(Q26 == 3, Q3FUS_Yes == "Yes") %>% 
  mutate(Switch = 0)

p14 <- data %>%
  filter(is.na(Q26), Q5Post == 1, Q3FUS_Yes == "Yes") %>%
  mutate(Switch = 0)

p15 <- data %>% 
  filter(is.na(Q26), Q5Post == 3, Q3FUS_Yes == "Yes") %>% 
  mutate(Switch = 0)

p16 <- data %>%
  filter(Q26 == 1, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)

p17 <- data %>% 
  filter(Q26 == 1, Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)

p18 <- data %>% 
  filter(Q26 == 1, Q5Post == 2, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes" ) %>%
  mutate(Switch = 0)

p19 <- data %>% 
  filter(Q26 == 1, is.na(Q5Post), Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)

p20 <- data %>%
  filter(Q26 == 3, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)
p21 <- data %>% 
  filter(Q26 == 3, Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)


p22 <- data %>%
  filter(Q26 == 3, Q5Post == 2, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes")  %>%
  mutate(Switch = 0)

p23 <- data %>%
  filter(Q26 == 3, is.na(Q5Post), Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes" )  %>%
  mutate(Switch = 0)

p24 <- data %>% 
  filter(is.na(Q26), Q5Post == 1, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)

p25 <- data %>%
  filter(is.na(Q26), Q5Post == 3, Q3Post == 1, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)

p26 <- data %>%
  filter(is.na(Q26), Q5Post == 3, Q3Post == 3, Q3FUS_No != "No", Q3FUS_Yes != "Yes") %>%
  mutate(Switch = 0)
```

```{r switchdata}

switchdata <- rbind(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,
                    s11,p12,p13,p14,p15,p16,p17,p18,
                    p19,p20,p21,p22,p23,p24,p25,p26)

```

```{r careerdata}
careerdata <- switchdata %>% 
  mutate(major = fct_collapse(factor(switchdata$Q60, levels=1:16), 
                              `1` = c("3","4","5","7","8","9"), 
                              `2` = "6", 
                              `3` = c("1","2"),
                              `4` = c("10","11","12","13","14","15"),
                              `5` = "16")) %>%
  
 filter(!(is.na(Q15_CalculusNonAPFinalGrade) & is.na(Q17_CalculusABFinalGrade) 
          & is.na(Q17_CalculusBCFinalGrade) & is.na(Q18))) %>% #filter cal exp
  
  filter(! is.na(major)) %>% #filter major
  
  filter(! (is.na(Q3_SATMath) & is.na(Q7_ACTMath))) %>% #filter no stnd test
  
  
  filter(Q3_SATMath %in% seq(200,800,10) | Q7_ACTMath %in% seq(1,36,1)) %>%
  
  filter(! is.na(Q48)) %>%#filter gender
  
  filter(! (is.na(Q18Post_Applications) & is.na(Q18Post_Appointments) & is.na(Q18Post_AskedQs)
            & is.na(Q18Post_Discouraged) & is.na(Q18Post_Explanations) &
              is.na(Q18Post_Listened) & is.na(Q18Post_ProblemSolver) &
              is.na(Q18Post_Time))) %>% #filer instruc qual
  
filter(! (is.na(Q19Post_SpecificProblems) & is.na(Q19Post_WorkTogether) &
            is.na(Q19Post_Discussion) & is.na(Q19Post_Presentations) &
            is.na(Q19Post_Individually) & is.na(Q19Post_Lecture) & is.na(Q19Post_AskQuestions)
          & is.na(Q19Post_ExplainThinking))) #filter student prep
  
```

```{r IQsetup}
## Instructor Quality 
IQ <- select(data, Q18Post_Applications, Q18Post_Appointments,
             Q18Post_AskedQs, Q18Post_Discouraged, Q18Post_Explanations,
             Q18Post_Listened, Q18Post_ProblemSolver, Q18Post_Time)

IQ$Q18Post_Discouraged <- 7-IQ$Q18Post_Discouraged

IQ <- na.omit(IQ)

pr_IQ <- princomp(IQ)

rescale_load_iq <- pr_IQ$loadings/sum(pr_IQ$loadings[,1])
```

```{r SCsetup}
## Student centered
SC <- select(data, Q19Post_AskQuestions, Q19Post_Discussion, 
             Q19Post_ExplainThinking, Q19Post_Individually,
             Q19Post_Lecture,Q19Post_Presentations,Q19Post_SpecificProblems,
             Q19Post_WorkTogether)

SC$Q19Post_Lecture <- 7 - SC$Q19Post_Lecture

SC <- na.omit(SC)

pr_SC <- princomp(SC)



rescale_load_sc <- pr_SC$loadings/sum(pr_SC$loadings[,1])

```

```{r putalltogether}
#Make variables for Instructor quality and student centered practices
IQcareer <- select(careerdata, Q18Post_Applications, Q18Post_Appointments, 
                   Q18Post_AskedQs, Q18Post_Discouraged, Q18Post_Explanations,
                   Q18Post_Listened, Q18Post_ProblemSolver, Q18Post_Time)

IQcareer$Q18Post_Discouraged <- 7-IQcareer$Q18Post_Discouraged

SCcareer <- select(careerdata, Q19Post_AskQuestions, Q19Post_Discussion,
                   Q19Post_ExplainThinking, Q19Post_Individually,
                   Q19Post_Lecture,Q19Post_Presentations,Q19Post_SpecificProblems, 
                   Q19Post_WorkTogether)

SCcareer$Q19Post_Lecture <- 7 - SCcareer$Q19Post_Lecture

careerdata <- careerdata %>% 
  mutate(Inst.Qual = 
           apply(IQcareer,1,weighted.mean,rescale_load_iq[,1],na.rm = TRUE))

careerdata <- careerdata %>%
  mutate(Student.Cent =
           apply(SCcareer,1,weighted.mean,rescale_load_sc[,1],na.rm = TRUE))

```

```{r percentiles}
X_SAT=careerdata$Q3_SATMath
SAT=rev(seq(200,800,by=10))
SAT_per=c(99,99, 99, 98, 97,97,96,95,95,94,93,
          91,90,88,87,85,83,82,79,77,75,73,70,
          67,64,62,59,55,52, 49,45,42,40,36,33,
          30,27,24,21,19,16,14,12,10,9, 7,6,5,4,
          3,3,2,2,1,1,1,1,1,0,0,0)

X_ACT=careerdata$Q7_ACTMath
ACT=36:1
ACT_per=c(99,99,99,98,97,96,95,93,91,88,84,79,
          73,67,61,56,52,47,42,36,27,15,6,2)
ACT_per=c(ACT_per, rep(1,length(ACT)-length(ACT_per)))

X_SAT=SAT_per[match(X_SAT, SAT)]

X_ACT= ACT_per[match(X_ACT, ACT)]
careerdata$x_per=rowMeans(cbind(X_SAT, X_ACT), na.rm=TRUE)

```

```{r calcdata}

calcdata <- careerdata %>% mutate(Prev_Calc = I((!(is.na(careerdata$Q15_CalculusNonAPFinalGrade)) 
                                           | !(is.na(careerdata$Q17_CalculusABFinalGrade)) 
                                           |  !(is.na(careerdata$Q17_CalculusBCFinalGrade))) 
                                          & (careerdata$Q18 == 2 | is.na(careerdata$Q18) ))*1 
                            
                            + I(careerdata$Q18 == 1 & !is.na(careerdata$Q18))*2 
                            
                            + I((is.na(careerdata$Q15_CalculusNonAPFinalGrade)) 
                                & (is.na(careerdata$Q17_CalculusABFinalGrade)) 
                                &  (is.na(careerdata$Q17_CalculusBCFinalGrade)) 
                                & (careerdata$Q18 == 2 | is.na(careerdata$Q18)) )*3)

calcdata$Prev_Calc <- as.factor(calcdata$Prev_Calc)

calcdata$major <- relevel(calcdata$major, ref = "1")

```

```{r final, warning = FALSE, fig.width=7}


mixM <- glmer(Switch ~ Prev_Calc + major + x_per + Inst.Qual 
              + Student.Cent + Q48 + (1|Institution),
              data = calcdata, family = "binomial", nAGQ = 10, 
              control = glmerControl("bobyqa",
                                     check.conv.grad = .makeCC("warning",tol = 1e-2))) 

sumMixM <- summary(mixM)

lower <- exp(sumMixM$coefficients[,1] - qnorm(.975) * sumMixM$coefficients[,2])
mean <- exp(sumMixM$coefficients[,1])
upper <- exp(sumMixM$coefficients[,1] + qnorm(.975) * sumMixM$coefficients[,2])

lower <- lower[-1]
mean <- mean[-1]
upper <- upper[-1]
group <- as.factor(c(1,1,3,2,3, 3, 2, 2,1, 3))

label <- c("College Calc", "No Previos Calc", "Pre-Med",
           "Engineer","Non-STEM","Undecided","Std Test", 
           "Instructor Qual", "Student Centered", "Female")


df <- data.frame(label, mean, lower, upper, group)

# reverses the factor level ordering for labels after coord_flip()
df$label <- factor(df$label, levels=rev(df$label))


fp <- ggplot(data=df, aes(x=label, y=mean, ymin=lower, ymax=upper, color = group)) +
        geom_pointrange() + 
        geom_hline(yintercept=1, lty=2) +  # add a dotted line at x=1 after flip
        coord_flip() +  # flip coordinates (puts labels on y axis)
        xlab("Label") + ylab("Odds Ratio") +
        theme_bw() +  # use a white background
        scale_y_continuous(limits=c(0,7)) + theme(legend.position = "None")
print(fp)


```



# Appendix

```{r show-code, ref.label = all_labels(),  echo = TRUE, eval = FALSE}

```
